"""Shared library behind the unified ``refresh_fixtures.py`` CLI.

Each offline test fixture is regenerated by a :class:`FixtureSource` that pairs

- ``refresh()`` — fetch the source live and write the fixture(s) atomically, and
- ``load()``    — read the *current on-disk* fixture(s) into a comparable
  :class:`Signature` so the CLI can diff before-vs-after and surface drift.

The value of the diff here is catching dtype / index-resolution shifts (the
recurring ``datetime64[s]``/``[ns]``/``[us]`` churn) and accidental shape
changes from a bad regeneration — *not* upstream column adds, which the live
``-m schema`` lane owns (the parsers extract fixed column lists).

Modules import only ``site_forecast.*`` so the scripts run under a plain
``uv run python`` without the pytest ``pythonpath``.
"""

from __future__ import annotations

import os
import tempfile
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterator, Optional

import pandas as pd
import xarray as xr


# .../tests/scripts/refresh/__init__.py -> parents[2] == .../tests
FIXTURES_DIR = Path(__file__).resolve().parents[2] / "fixtures"


@dataclass(frozen=True)
class Signature:
    """Structural fingerprint of one fixture file, comparable across refreshes."""

    kind: str  # "frame" or "dataset"
    columns: dict[str, str]  # column / data_var name -> dtype
    index: dict[str, str]  # index-level -> dtype (frame) or dim -> size (dataset)
    shape: tuple[int, ...]


@dataclass(frozen=True)
class FixtureSource:
    name: str
    refresh: Callable[[], None]
    # ``None`` for sources whose fixture cannot be signature-diffed (cassettes);
    # such a ``refresh`` verifies itself and the CLI skips the diff.
    load: Optional[Callable[[], dict[str, Signature]]] = None


def _index_dtypes(index: pd.Index) -> dict[str, str]:
    if isinstance(index, pd.MultiIndex):
        return {str(name): str(dt) for name, dt in index.dtypes.items()}
    return {str(index.name): str(index.dtype)}


def dataframe_signature(df: pd.DataFrame) -> Signature:
    return Signature(
        kind="frame",
        columns={str(c): str(df[c].dtype) for c in df.columns},
        index=_index_dtypes(df.index),
        shape=tuple(df.shape),
    )


def dataset_signature(ds: xr.Dataset) -> Signature:
    return Signature(
        kind="dataset",
        columns={str(v): str(ds[v].dtype) for v in ds.data_vars},
        index={str(d): str(ds.sizes[d]) for d in ds.dims},
        shape=tuple(ds.sizes[d] for d in ds.dims),
    )


@contextmanager
def atomic_write(final_path: Path) -> Iterator[Path]:
    """Yield a temp path in ``final_path``'s directory; ``os.replace`` it into
    place on clean exit so a failed fetch never clobbers a good committed
    fixture."""
    final_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=final_path.parent, prefix=f".{final_path.name}.", suffix=".tmp"
    )
    os.close(fd)
    tmp_path = Path(tmp_name)
    try:
        yield tmp_path
        os.replace(tmp_path, final_path)
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


def _diff_mapping(
    label: str, kind: str, old: dict[str, str], new: dict[str, str]
) -> list[str]:
    """Lines describing added/dropped keys and value changes between two maps."""
    what = "data_var" if kind == "dataset" else "column"
    lines: list[str] = []
    for key in sorted(new.keys() - old.keys()):
        lines.append(f"    + {what} {key} ({new[key]})")
    for key in sorted(old.keys() - new.keys()):
        lines.append(f"    - {what} {key} ({old[key]})")
    for key in sorted(old.keys() & new.keys()):
        if old[key] != new[key]:
            lines.append(f"    ~ {what} {key}: {old[key]} -> {new[key]}")
    return lines


def render_diff(
    name: str,
    before: dict[str, Signature],
    after: dict[str, Signature],
) -> str:
    """Human-readable diff of a source's fixtures before vs. after a refresh."""
    lines = [f"[{name}] diff vs. previous fixture:"]
    labels = sorted(before.keys() | after.keys())
    for label in labels:
        old, new = before.get(label), after.get(label)
        if old is None:
            lines.append(f"  {label}: new fixture ({new.kind}, shape={new.shape})")
            continue
        if new is None:
            lines.append(f"  {label}: fixture no longer written")
            continue
        body = _diff_mapping(label, new.kind, old.columns, new.columns)
        idx_word = "dim" if new.kind == "dataset" else "index"
        for k in sorted(old.index.keys() | new.index.keys()):
            ov, nv = old.index.get(k), new.index.get(k)
            if ov != nv:
                body.append(f"    ~ {idx_word} {k}: {ov} -> {nv}")
        if old.shape != new.shape:
            body.append(f"    ~ shape: {old.shape} -> {new.shape}")
        if body:
            lines.append(f"  {label}:")
            lines.extend(body)
        else:
            lines.append(f"  {label}: no change (shape={new.shape})")
    return "\n".join(lines)
