"""Offline tests for ``ApiQuery`` and ``WeatherStationQuery``.

The DB connection is intercepted at ``psycopg2.connect`` so
``MonitorConnection``'s real ``fetch_rows`` runs against pre-captured raw
rowsets (list[tuple]) — this means ``parse_rows`` and
``rowset_to_dataframe`` actually execute against representative data and
the offline test covers them, while the network/DB hop is replaced.

Fixtures live at ``tests/fixtures/dataframes/monitor_*_rows.pkl.gz`` and
are regenerated by ``tests/scripts/refresh_fixtures.py monitor``.
"""

from __future__ import annotations

import gzip
import pickle
from unittest.mock import MagicMock

import pytest

import site_forecast.query.monitor as monitor_mod
from site_forecast.query.monitor import ApiQuery, WeatherStationQuery

from schemas.queries import ApiQuerySchema, WeatherStationSchema


def _load_rowsets(path):
    with gzip.open(path, "rb") as f:
        return pickle.load(f)


def _install_mock_connection(monkeypatch, rowsets):
    """Wire ``psycopg2.connect`` to a mock that yields ``rowsets`` from
    successive ``cursor.fetchall()`` calls in the order they're issued."""
    mock_cursor = MagicMock()
    mock_cursor.fetchall.side_effect = list(rowsets)
    mock_conn = MagicMock()
    mock_conn.cursor.return_value.__enter__.return_value = mock_cursor

    def fake_connect(**kwargs):
        return mock_conn

    monkeypatch.setattr(monitor_mod.psycopg2, "connect", fake_connect)
    return mock_conn, mock_cursor


@pytest.fixture
def api_fixture(dataframes_dir):
    return _load_rowsets(dataframes_dir / "monitor_api_rows.pkl.gz")


@pytest.fixture
def weather_fixture(dataframes_dir):
    return _load_rowsets(dataframes_dir / "monitor_weather_rows.pkl.gz")


def test_api_query_replays_rowsets_and_is_okay(monkeypatch, api_fixture):
    _install_mock_connection(monkeypatch, api_fixture["rowsets"])
    q = ApiQuery(mjd_start=api_fixture["mjd_start"], mjd_end=api_fixture["mjd_end"])
    assert q.okay
    ApiQuerySchema.validate(q.df)


def test_api_query_recent_and_complete_within_fixture_window(monkeypatch, api_fixture):
    """Both predicates use ``forecast_time`` (derived from ``mjd_end``) vs.
    the fixture's data span, so they're stable against wall-clock time."""
    _install_mock_connection(monkeypatch, api_fixture["rowsets"])
    q = ApiQuery(mjd_start=api_fixture["mjd_start"], mjd_end=api_fixture["mjd_end"])
    assert q.is_recent
    assert q.is_complete


def test_api_query_to_model_series_is_resampled_to_15min(monkeypatch, api_fixture):
    _install_mock_connection(monkeypatch, api_fixture["rowsets"])
    q = ApiQuery(mjd_start=api_fixture["mjd_start"], mjd_end=api_fixture["mjd_end"])
    ts = q.to_model_series()
    assert ts is not None
    assert ts.freq_str.lower().startswith("15")


def test_api_query_save_data_writes_parquet(monkeypatch, api_fixture, tmp_path):
    _install_mock_connection(monkeypatch, api_fixture["rowsets"])
    q = ApiQuery(mjd_start=api_fixture["mjd_start"], mjd_end=api_fixture["mjd_end"])
    out_root = tmp_path / "forecasts"
    monkeypatch.setattr(ApiQuery, "forecast_dir", property(lambda self: out_root))
    q.save_data(outname="api")
    assert (out_root / "api.parquet").exists()


def test_weather_query_replays_rowsets_and_is_okay(monkeypatch, weather_fixture):
    _install_mock_connection(monkeypatch, weather_fixture["rowsets"])
    q = WeatherStationQuery(
        mjd_start=weather_fixture["mjd_start"],
        mjd_end=weather_fixture["mjd_end"],
    )
    assert q.okay
    WeatherStationSchema.validate(q.df)


def test_weather_query_recent_and_complete(monkeypatch, weather_fixture):
    _install_mock_connection(monkeypatch, weather_fixture["rowsets"])
    q = WeatherStationQuery(
        mjd_start=weather_fixture["mjd_start"],
        mjd_end=weather_fixture["mjd_end"],
    )
    assert q.is_recent
    assert q.is_complete


# MonitorConnection.__del__ unconditionally touches self.connection, which
# wasn't set if psycopg2.connect raised — the resulting unraisable warning
# is unrelated to what we're asserting here.
@pytest.mark.filterwarnings("ignore::pytest.PytestUnraisableExceptionWarning")
def test_query_okay_false_when_connection_fails(monkeypatch):
    """If ``psycopg2.connect`` raises, the query swallows the exception
    and ends up with ``df is None`` (okay=False)."""

    def boom(**kwargs):
        raise RuntimeError("simulated DB failure")

    monkeypatch.setattr(monitor_mod.psycopg2, "connect", boom)
    q = ApiQuery(mjd_start=61000.0, mjd_end=61000.5)
    assert q.df is None
    assert not q.okay
