"""Tests for the AM sensitivity estimator beyond the pure helpers.

Three concerns, all offline (the AM model is a local subprocess, no network):

- **Profile prep** — ``AmModelPredictor`` clips/clamps atmospheric profiles
  deterministically; asserted without running AM.
- **Real-AM smoke** — ``AmModelPredictor.run`` and ``VlaSeasonalPredictor.run``
  actually invoke amwrap (~0.5 s each) to guard the radiative-transfer
  integration.
- **Estimator assembly** — ``VlaSensitivityEstimator`` orchestration. The
  clear-sky path runs real AM on a truncated input; the branchy cloud/ensemble
  MultiIndex assembly is covered with ``_run_am_model`` monkeypatched (running
  it for real would be one AM model per timestep x quantile).

Input weather comes from ``tests/fixtures/sensitivity/om_{surface,pressure}.parquet``
(regenerated by ``tests/scripts/refresh_sensitivity_fixtures.py``); the cloud
path reuses the Herbie fixture.
"""

from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import numpy as np
import pandas as pd
import pytest
import xarray as xr

from site_forecast.query import herbie_maps as hm
from site_forecast.query.herbie_maps import HerbieQuery
from site_forecast.sensitivity import (
    AmModelPredictor,
    VlaSeasonalPredictor,
    VlaSensitivityEstimator,
)

from schemas.queries import OpenMeteoVlaSchema, OpenMeteoVlaPressureSchema


TESTS_DIR = Path(__file__).parents[1]
SENSITIVITY_DIR = TESTS_DIR / "fixtures" / "sensitivity"
HERBIE_FIXTURE = TESTS_DIR / "fixtures" / "dataframes" / "herbie_tcolw_tiny.nc"


@pytest.fixture(scope="module")
def om_surface() -> pd.DataFrame:
    return pd.read_parquet(SENSITIVITY_DIR / "om_surface.parquet")


@pytest.fixture(scope="module")
def om_pressure() -> pd.DataFrame:
    return pd.read_parquet(SENSITIVITY_DIR / "om_pressure.parquet")


@pytest.fixture(scope="module")
def shared_times(om_surface, om_pressure) -> pd.DatetimeIndex:
    """Hourly timestamps present in both frames (the estimator intersects them)."""
    pres_dates = om_pressure.index.get_level_values("date").unique()
    return pres_dates.intersection(om_surface.index)


@pytest.fixture(scope="module")
def herbie_tcolw_ds():
    """A real reduced Herbie ``tcolw`` dataset (with ``tcolw_q`` at 10/20 km),
    built by replaying the Herbie fixture through the actual query pipeline."""
    with patch.object(
        hm,
        "get_tcolw",
        lambda **kwargs: xr.load_dataset(HERBIE_FIXTURE),
    ):
        return HerbieQuery(query_type="tcolw").ds


# ---------------------------------------------------------------------------
# Layer 1 — input fixture contract
# ---------------------------------------------------------------------------


def test_input_fixtures_satisfy_open_meteo_schemas(om_surface, om_pressure):
    # Parquet stores the datetime index at coarser (ms) resolution than the
    # live query's [s]; normalise before validating against the [s]-pinned
    # schemas. Structural columns/dtypes are what we're guarding here.
    surf = om_surface.copy()
    surf.index = surf.index.as_unit("s")
    pres = om_pressure.copy()
    pres.index = pres.index.set_levels(pres.index.levels[0].as_unit("s"), level="date")
    OpenMeteoVlaSchema.validate(surf)
    OpenMeteoVlaPressureSchema.validate(pres)


# ---------------------------------------------------------------------------
# Layer 2 — AmModelPredictor profile prep (no AM run)
# ---------------------------------------------------------------------------


def test_am_predictor_profile_prep_from_frames(om_surface, om_pressure, shared_times):
    t = shared_times[0]
    predictor = AmModelPredictor.from_frames(
        om_surface.loc[t], om_pressure.xs(t, level="date")
    )

    # Profiles are aligned and pressure is monotically descending.
    n = len(predictor.pres)
    assert len({n, len(predictor.temp), len(predictor.relh), len(predictor.mixr)}) == 1
    assert predictor.pres[0] > predictor.pres[-1]

    # Reference PWV is positive and pwv_scale is the target/model ratio.
    assert predictor.model_pwv.to("mm").value > 0
    assert np.isclose(
        predictor.pwv_scale, (predictor.pwv / predictor.model_pwv).to("").value
    )

    # Stratospheric water is clamped up to the floor; humidity floored to eps.
    strato = predictor.pres < predictor.strato_pressure_limit
    if strato.any():
        floor = predictor.strato_mixing_ratio.to("").value
        assert np.all(predictor.mixr[strato].to("").value >= floor)
    assert np.all(
        predictor.relh.to("").value >= predictor.relative_humidity_epsilon.value
    )


# ---------------------------------------------------------------------------
# Layer 3 — real-AM smoke (default lane; ~0.5 s each)
# ---------------------------------------------------------------------------

_SPECTRAL_COLS = {"brightness_temperature", "opacity", "transmittance"}


def test_am_predictor_run_smoke(om_surface, om_pressure, shared_times):
    t = shared_times[0]
    predictor = AmModelPredictor.from_frames(
        om_surface.loc[t], om_pressure.xs(t, level="date")
    )
    df = predictor.run()
    assert df.index.names == ["date", "frequency"]
    assert _SPECTRAL_COLS.issubset(df.columns)
    assert len(df) > 0


def test_seasonal_predictor_run_smoke():
    df = VlaSeasonalPredictor(pd.Timestamp("2025-07-15")).run()
    assert df.index.name == "frequency"
    assert _SPECTRAL_COLS.issubset(df.columns)


# ---------------------------------------------------------------------------
# Layer 4 — derived sensitivity columns (known answer)
# ---------------------------------------------------------------------------


def test_add_derived_columns_known_answer():
    est = object.__new__(VlaSensitivityEstimator)  # skip __init__ (no AM run)
    idx = pd.MultiIndex.from_tuples(
        [(pd.Timestamp("2025-01-01"), "L"), (pd.Timestamp("2025-01-01"), "S")],
        names=["date", "band"],
    )
    df = pd.DataFrame(
        {
            "brightness_temperature": [10.0, 20.0],
            "opacity": [0.1, 0.2],
            "transmittance": [0.9, 0.8],
        },
        index=idx,
    )
    baseline = pd.DataFrame(
        {
            "brightness_temperature": [5.0, 5.0],
            "opacity": [0.05, 0.05],
            "transmittance": [0.95, 0.95],
        },
        index=pd.Index(["L", "S"], name="band"),
    )

    out = est._add_derived_columns(df, baseline)

    rt = VlaSensitivityEstimator.receiver_temperatures["L"]
    tsys, tsys_cl = 10.0 + rt, 5.0 + rt
    assert out.loc[idx[0], "system_temperature"] == pytest.approx(tsys)
    assert out.loc[idx[0], "system_temperature_cl"] == pytest.approx(tsys_cl)
    expected = (0.95 / 0.9) * (tsys / tsys_cl)
    assert out.loc[idx[0], "eff_sensitivity"] == pytest.approx(expected)
    assert out.loc[idx[0], "eff_time"] == pytest.approx(expected**2)


# ---------------------------------------------------------------------------
# Layer 5 — TCOLW quantile extraction from a Herbie dataset
# ---------------------------------------------------------------------------


def test_get_tcolw_df_extracts_quantiles(herbie_tcolw_ds):
    est = object.__new__(VlaSensitivityEstimator)
    est.clwp_query = SimpleNamespace(ds=herbie_tcolw_ds, okay=True)
    df = est._get_tcolw_df()

    assert df.index.name == "date"
    assert df.index.tz is not None
    # 21 spatial quantiles (0..1) at the selected radius.
    assert df.columns.name == "quantile"
    assert len(df.columns) == 21
    assert float(df.columns.min()) == 0.0
    assert float(df.columns.max()) == 1.0


# ---------------------------------------------------------------------------
# Layer 6 — estimator clear-sky path end-to-end (real AM, truncated input)
# ---------------------------------------------------------------------------


def _fake_query(df=None, okay=True, forecast_time=None, ds=None) -> SimpleNamespace:
    return SimpleNamespace(df=df, okay=okay, forecast_time=forecast_time, ds=ds)


def test_estimator_clear_path_end_to_end(om_surface, om_pressure, shared_times):
    """Full construct + compute over two shared timesteps, running real AM
    single-threaded. Only the clear-sky path is populated (no cloud/ensemble),
    so `okay` (which requires both frames) is False."""
    times = shared_times[:2]
    surf = _fake_query(df=om_surface.loc[times], okay=True, forecast_time=times[0])
    pres = _fake_query(
        df=om_pressure[om_pressure.index.get_level_values("date").isin(times)],
        okay=True,
    )

    est = VlaSensitivityEstimator(surf, pres, None, n_workers=1)

    assert est.clear_df is not None
    assert est.clear_df.index.names == ["date", "band"]
    assert "eff_sensitivity" in est.clear_df.columns
    assert est.cloud_df is None
    assert est.okay is False


def test_estimator_clear_path_uses_worker_pool(om_surface, om_pressure, shared_times):
    """Same clear-sky path with ``n_workers=2``, so ``_run_series`` takes the real
    ``multiprocessing.Pool`` branch: ``_worker_init`` runs in each forked worker
    (building/cleaning its own AM cache dir via ``_get_worker_cache_path``), the
    AM args pickle across the process boundary, real AM runs there, and results
    aggregate back. Guards the pool path production uses at ``n_workers=20``."""
    times = shared_times[:2]
    surf = _fake_query(df=om_surface.loc[times], okay=True, forecast_time=times[0])
    pres = _fake_query(
        df=om_pressure[om_pressure.index.get_level_values("date").isin(times)],
        okay=True,
    )

    est = VlaSensitivityEstimator(surf, pres, None, n_workers=2)

    assert est.clear_df is not None
    assert est.clear_df.index.names == ["date", "band"]
    assert "eff_sensitivity" in est.clear_df.columns
    # Every timestep round-tripped through the pool: n_timesteps x n_bands rows.
    n_bands = len(VlaSensitivityEstimator.band_frequencies)
    assert len(est.clear_df) == len(times) * n_bands
    assert set(est.clear_df.index.get_level_values("date")) == set(times)


# ---------------------------------------------------------------------------
# Layer 7 — cloud/ensemble MultiIndex assembly (AM mocked)
# ---------------------------------------------------------------------------


def _band_frame() -> pd.DataFrame:
    bands = list(VlaSensitivityEstimator.band_frequencies)
    return pd.DataFrame(
        {"brightness_temperature": 1.0, "opacity": 0.1, "transmittance": 0.9},
        index=pd.Index(bands, name="band"),
    )


def _fake_run_am_model(*args):
    """Stand in for the AM worker: return a synthetic band frame with the same
    tuple shape the real function uses. The 13-arg form (trailing pwv_series)
    is the ensemble path; otherwise it's the per-quantile cloud path."""
    time = args[0]
    if len(args) == 13 and args[12] is not None:  # ensemble: pwv_series present
        return time, None, {member: _band_frame() for member in args[12].index}
    return time, args[8], _band_frame()  # cloud: args[8] is the quantile


def _bare_estimator() -> VlaSensitivityEstimator:
    est = object.__new__(VlaSensitivityEstimator)
    est.n_workers = 1  # direct calls, not multiprocessing.Pool
    est.ciwp_query = None  # has_cloud_ice -> False
    return est


def test_run_series_cloud_assembly(monkeypatch, om_surface, om_pressure, shared_times):
    monkeypatch.setattr("site_forecast.sensitivity._run_am_model", _fake_run_am_model)
    times = shared_times[:2]
    surf = om_surface.loc[times]
    pres = om_pressure[om_pressure.index.get_level_values("date").isin(times)]
    tcolw_df = pd.DataFrame(
        [[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]],
        index=pd.DatetimeIndex(times, name="date"),
        columns=pd.Index([0.0, 0.5, 1.0], name="quantile"),
    )

    out = _bare_estimator()._run_series(surf, pres, tcolw_df=tcolw_df)

    assert out.index.names == ["date", "band", "quantile"]
    assert set(out.index.get_level_values("quantile")) == {0.0, 0.5, 1.0}


def test_run_series_ensemble_assembly(
    monkeypatch, om_surface, om_pressure, shared_times
):
    monkeypatch.setattr("site_forecast.sensitivity._run_am_model", _fake_run_am_model)
    times = shared_times[:2]
    surf = om_surface.loc[times]
    pres = om_pressure[om_pressure.index.get_level_values("date").isin(times)]
    ens_idx = pd.MultiIndex.from_product([times, [0, 1]], names=["date", "member"])
    ensemble_pwv_df = pd.DataFrame(
        {"total_column_integrated_water_vapour": np.linspace(5, 10, len(ens_idx))},
        index=ens_idx,
    )

    out = _bare_estimator()._run_series(surf, pres, ensemble_pwv_df=ensemble_pwv_df)

    assert out.index.names == ["date", "band", "member"]
    assert set(out.index.get_level_values("member")) == {0, 1}


# ---------------------------------------------------------------------------
# Layer 8 — degrade-gracefully + persistence
# ---------------------------------------------------------------------------


def test_estimator_skips_when_weather_unavailable(shared_times):
    """A failed surface query short-circuits without raising; both outputs are
    None and okay is False."""
    surf = _fake_query(df=None, okay=False, forecast_time=shared_times[0])
    pres = _fake_query(df=None, okay=True)

    est = VlaSensitivityEstimator(surf, pres, None, n_workers=1)

    assert est.clear_df is None
    assert est.cloud_df is None
    assert est.okay is False


def test_save_data_writes_parquet(monkeypatch, tmp_path):
    est = object.__new__(VlaSensitivityEstimator)
    est.clear_df = pd.DataFrame(
        {"eff_sensitivity": [1.0, 1.1]},
        index=pd.MultiIndex.from_tuples(
            [(pd.Timestamp("2025-01-01"), "L"), (pd.Timestamp("2025-01-01"), "S")],
            names=["date", "band"],
        ),
    )
    est.cloud_df = None
    monkeypatch.setattr(
        VlaSensitivityEstimator, "forecast_dir", property(lambda self: tmp_path)
    )

    est.save_data()

    assert (tmp_path / "vla_sensitivity.parquet").exists()
